import streamlit as st
import pandas as pd
import plotly.express as px
import numpy as np

# Set page config
st.set_page_config(page_title="Laptop Analytics Pro", layout="wide")

# Load the cleaned data generated by your automation script
@st.cache_data(ttl=5)  # Short TTL to ensure it catches real-time Excel updates
@st.cache_data(ttl=5)
def load_data():
    df = pd.read_excel('laptops_cleaned_automated.xlsx')
    # Force specific categorical columns to string to prevent 'int' vs 'str' errors
    cols_to_fix = ['brand', 'OS', 'cpu', 'graphics', 'color', 'special_features']
    for col in cols_to_fix:
        if col in df.columns:
            df[col] = df[col].astype(str).replace('nan', np.nan).replace('Unknown', np.nan)
    return df

# --- UPDATE THE SIDEBAR FILTERS SECTION ---
try:
    df = load_data()
    
    st.sidebar.header("🔍 Global Filters")
    
    # helper to get clean, sorted unique values
    def get_options(column_name):
        return sorted(df[column_name].dropna().unique().tolist())

    # 1. Brand & OS
    brand_filter = st.sidebar.multiselect("Select Brand", options=get_options('brand'), default=get_options('brand'))
    os_filter = st.sidebar.multiselect("Select OS", options=get_options('OS'), default=get_options('OS'))

    # 2. Technical Specs
    cpu_filter = st.sidebar.multiselect("Select CPU", options=get_options('cpu'), default=get_options('cpu'))
    gpu_filter = st.sidebar.multiselect("Select Graphics", options=get_options('graphics'), default=get_options('graphics'))

    # 3. Visuals
    color_filter = st.sidebar.multiselect("Select Color", options=get_options('color'), default=get_options('color'))

    # 4. Special Features
    feature_filter = st.sidebar.multiselect("Filter by Special Features", options=get_options('special_features'))

    # --- APPLY FILTERS ---
    mask = (
        df['brand'].isin(brand_filter) & 
        df['OS'].isin(os_filter) & 
        df['cpu'].isin(cpu_filter) &
        df['graphics'].isin(gpu_filter) &
        df['color'].isin(color_filter)
    )
    
    filtered_df = df[mask].copy() # Use .copy() to avoid SettingWithCopy warnings

    # Special Filter for 'Special Features' (Sub-string matching)
    if feature_filter:
        pattern = '|'.join(feature_filter)
        filtered_df = filtered_df[filtered_df['special_features'].str.contains(pattern, na=False)]

    # --- 1. KPI SECTION ---
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Revenue", f"${filtered_df['Total Sales'].sum():,.2f}")
    with col2:
        st.metric("Avg. Price", f"${filtered_df['Price'].mean():,.2f}")
    with col3:
        st.metric("Units Sold", f"{int(filtered_df['Sale Product Count'].sum())}")
    with col4:
        st.metric("Stock Available", f"{int(filtered_df['Available Stock'].sum())}")

    st.markdown("---")

    # --- 2. PRICE ANALYSIS (Dynamic Columns Check) ---
    st.subheader("🔍 Price Analysis by Features")
    
    # We check which columns actually exist (in case the cleaner dropped some)
    potential_x = ['ram', 'harddisk', 'screen_size', 'rating', 'cpu_speed']
    available_x = [col for col in potential_x if col in filtered_df.columns]

    if available_x:
        feature_x = st.selectbox("Select Feature to compare with Price", options=available_x)
        fig_price = px.scatter(
            filtered_df, x=feature_x, y='Price', 
            color='brand', hover_name='model',
            title=f"Price vs {feature_x.replace('_', ' ').capitalize()}",
            template="plotly_white"
        )
        st.plotly_chart(fig_price, use_container_width=True)
    else:
        st.info("Add more data to the Excel file to unlock feature analysis.")

    # --- 3. REVENUE BY BRAND & MODEL ---
    col_a, col_b = st.columns(2)

    with col_a:
        st.subheader("🏢 Revenue by Brand")
        brand_rev = filtered_df.groupby('brand')['Total Sales'].sum().reset_index()
        fig_brand = px.pie(brand_rev, values='Total Sales', names='brand', hole=0.4)
        st.plotly_chart(fig_brand, use_container_width=True)

    with col_b:
        st.subheader("📦 Revenue by Brand & Model")
        # Treemap for hierarchical view
        fig_tree = px.treemap(
            filtered_df, path=['brand', 'model'], values='Total Sales',
            color='Total Sales', color_continuous_scale='RdBu'
        )
        st.plotly_chart(fig_tree, use_container_width=True)

    # --- 4. TOP SELLING PRODUCTS ---
    st.subheader("🏆 Top-Selling Products")
    top_products = filtered_df.nlargest(10, 'Sale Product Count')[
        ['brand', 'model', 'color', 'cpu', 'Sale Product Count', 'Total Sales']
    ]
    st.dataframe(top_products, use_container_width=True)

except Exception as e:
    st.error(f"Waiting for updated data from Excel... ")
    st.info(f"Technical Detail: {e}")